name: "Meta Targeting 7"
on:
  schedule:
    - cron: '0 2,5,8,11,14,17,21,23 * * *'
  push:
    branches:
      - main
      
jobs:
  update-nl-nieuws:
    name: Update 
    runs-on: windows-latest
    permissions:
      contents: write
    env:
      GITHUB_PAT: ${{ secrets.GH_PAT }}
    steps:
      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: 'release'
      - name: Setup - Checkout repo
        uses: actions/checkout@v3
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          cache-version: 1
          needs: |
            any::tidyverse
            any::newsanchor
            any::janitor
            any::arrow
            any::piggyback
      - name: "Script - Update Nieuws
        run: Rscript 'retrieve_nieuws.R'